name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u itlinux --password $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag itlinux/node-test:$(date +%s)

      - name: Docker Push
        run: docker push itlinux/node-test
